Montréal
========
:revnumber: 0.1-draft.1

A RISC-V RV32E processor designed for TinyTapeout.

Github repository:
https://github.com/ubc-asic/superscalar-summer/tree/master

Instruction Set
---------------

https://docs.riscv.org/reference/isa/unpriv/unpriv-index.html[ISA Reference]

.Relevant opcodes for the IP. `inst[1:0] = 11`.
[cols="10*^1m"]
|===

h|
h|
8+^h| `inst[4:2]`

h|
h|
h| `000`
h| `001`
h| `010`
h| `011`
h| `100`
h| `101`
h| `110`
h| `111`

1.4+.^h| `inst[6:5]`
h| `00`
| LOAD
|
|
| MISC-MEM
| OP-IMM
| AUIPC
|
|

h| `01`
| STORE
|
|
|
| OP
| LUI
|
|

h| `10`
|
|
|
|
|
|
|
|

h| `11`
| BRANCH
| JALR
|
| JAL
| SYSTEM
|
|
|
|===

=== LUI

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x37, attr: "LUI" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 20, name: "imm[31:12]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "LUI" }
	}
}
....

=== AUIPC

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x17, attr: "AUIPC" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 20, name: "imm[31:12]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "AUIPC" }
	}
}
....

=== OP-IMM

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "ADDI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 2, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "SLTI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 3, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "SLTIU" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 4, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "XORI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 6, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "ORI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 7, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 },
	],
	config: {
		fontsize: 12,
		label: { right: "ANDI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 1, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "shamt", type: 7 },
		{ bits: 7, name: 0, attr: "imm[11:5]" }
	],
	config: {
		fontsize: 12,
		label: { right: "SLLI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "shamt", type: 7 },
		{ bits: 7, name: 0, attr: "imm[11:5]" }
	],
	config: {
		fontsize: 12,
		label: { right: "SRLI" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x13, attr: "OP-IMM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "shamt", type: 7 },
		{ bits: 7, name: 0x20, attr: "imm[11:5]" }
	],
	config: {
		fontsize: 12,
		label: { right: "SRAI" }
	}
}
....

=== OP

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "ADD" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0x20, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SUB" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 2, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SLT" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 3, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SLTU" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 4, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "XOR" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 6, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "OR" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 7, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "AND" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 1, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SLL" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SRL" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 0x20, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "SRA" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 7, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "CZERO.EQZ" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x33, attr: "OP" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 7, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: 7, attr: "funct7" }
	],
	config: {
		fontsize: 12,
		label: { right: "CZERO.NEZ" }
	}
}
....

=== JAL

The labels `[11]` and `[20]` represent the bits `imm[11]` and `imm[20]` respectively.

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x6f, attr: "JAL" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 8, name: "imm[19:12]", type: 7 },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 10, name: "imm[10:1]", type: 7 },
		{ bits: 1, name: "[20]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "JAL" }
	}
}
....

=== JALR

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x67, attr: "JALR" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "JALR" }
	}
}
....

=== BRANCH

The labels `[11]` and `[12]` represent the bits `imm[11]` and `imm[12]` respectively.

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BEQ" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 1, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BNE" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 4, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BLT" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BGE" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 6, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BLTU" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x63, attr: "BRANCH" },
		{ bits: 1, name: "[11]", type: 7 },
		{ bits: 4, name: "imm[4:1]", type: 7 },
		{ bits: 3, name: 7, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 6, name: "imm[10:5]", type: 7 },
		{ bits: 1, name: "[12]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "BGEU" }
	}
}
....

=== LOAD

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x03, attr: "LOAD" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "LB" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x03, attr: "LOAD" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 1, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "LH" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x03, attr: "LOAD" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 2, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "LW" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x03, attr: "LOAD" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 4, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "LBU" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x03, attr: "LOAD" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 5, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 12, name: "imm[11:0]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "LHU" }
	}
}
....

=== STORE

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x23, attr: "STORE" },
		{ bits: 5, name: "imm[4:0]", type: 7 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: "imm[11:5]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "SB" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x23, attr: "STORE" },
		{ bits: 5, name: "imm[4:0]", type: 7 },
		{ bits: 3, name: 1, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: "imm[11:5]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "SH" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x23, attr: "STORE" },
		{ bits: 5, name: "imm[4:0]", type: 7 },
		{ bits: 3, name: 2, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 5, name: "rs2", type: 2 },
		{ bits: 7, name: "imm[11:5]", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "SW" }
	}
}
....

=== MISC-MEM

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x0f, attr: "MISC-MEM" },
		{ bits: 5, name: "rd", type: 2 },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: "rs1", type: 2 },
		{ bits: 4, name: "pred", type: 7 },
		{ bits: 4, name: "succ", type: 7 },
		{ bits: 4, name: "fm", type: 7 }
	],
	config: {
		fontsize: 12,
		label: { right: "FENCE" }
	}
}
....

=== SYSTEM

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x73, attr: "SYSTEM" },
		{ bits: 5, name: 0, attr: "rd" },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: 0, attr: "rs1" },
		{ bits: 12, name: 0, attr: "imm[11:0]" }
	],
	config: {
		fontsize: 12,
		label: { right: "ECALL" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 7, name: 0x73, attr: "SYSTEM" },
		{ bits: 5, name: 0, attr: "rd" },
		{ bits: 3, name: 0, attr: "funct3" },
		{ bits: 5, name: 0, attr: "rs1" },
		{ bits: 12, name: 1, attr: "imm[11:0]" }
	],
	config: {
		fontsize: 12,
		label: { right: "EBREAK" }
	}
}
....

=== Immediate Types

The labels `[7]` and `[20]` represent the bits `inst[7]` and `inst[20]`, respectively.

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 12, name: "inst[31:20]", attr: "12" },
		{ bits: 20, name: "inst[31]", attr: "20" }
	],
	config: {
		fontsize: 12,
		label: { right: "I-immediate" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 5, name: "inst[11:7]", attr: "5" },
		{ bits: 7, name: "inst[31:25]", attr: "7" },
		{ bits: 20, name: "inst[31]", attr: "20" }
	],
	config: {
		fontsize: 12,
		label: { right: "S-immediate" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 1, name: "0", attr: "1" },
		{ bits: 4, name: "inst[11:8]", attr: "4" },
		{ bits: 6, name: "inst[30:25]", attr: "6" },
		{ bits: 1, name: "[7]", attr: "1" },
		{ bits: 20, name: "inst[31]", attr: "20" }
	],
	config: {
		fontsize: 12,
		label: { right: "B-immediate" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 12, name: "0", attr: "12" },
		{ bits: 20, name: "inst[31:12]", attr: "20" },
	],
	config: {
		fontsize: 12,
		label: { right: "U-immediate" }
	}
}
....

[wavedrom, format=svg]
....
{
	reg: [
		{ bits: 1, name: "0", attr: "1" },
		{ bits: 10, name: "inst[30:21]", attr: "10" },
		{ bits: 1, name: "[20]", attr: "1" },
		{ bits: 8, name: "inst[19:12]", attr: "8" },
		{ bits: 12, name: "inst[31]", attr: "12" }
	],
	config: {
		fontsize: 12,
		label: { right: "J-immediate" }
	}
}
....
